### ISSUE TITLE
Missing projects?

### ISSUE THREAD

**Issue by NicoMeijerman** [markolbert/J4JMapControl#1] opened 2023-08-22 12:38 UTC
I cloned your J4JMapControl from GitHub but already when opening the solution file I get an error message about missing project files:
- C:\...\ProgrammingUtilities\VisualUtilities\VisualUtilities.csproj : error  : The project file cannot be found.
- C:\...\ProgrammingUtilities\WindowsUtilities\WindowsUtilities.csproj : error  : The project file cannot be found.

And of course building doesn't work. 
But perhaps I am missing something, this is the first time I get code from GitHub...

**Comment by markolbert** [comment] 2023-08-22 17:00
Hi Nico, and sorry you're running into issues.

What branch are you cloning? If you're not using main/master, please switch to that. The other branches will not necessarily compile on someone else's machine.

Also, can you share the context where the error messages are showing up? I presume it's someplace other than when you do a build. But when/where are they appearing? When the solution loads? Or someplace else?

**Comment by NicoMeijerman** [comment] 2023-08-23 11:18
Hi Mark, 

First of all, thanks for the fast response. I am using the master branch, did a fetch yesterday so it should be the latest greatest.
I get the error message directly when opening the solution file. So it looks like you still refer to the VisualUtilities and WindowsUtilities project files.

The error message when loading the solution:
![image](https://github.com/markolbert/J4JMapControl/assets/105173283/07513159-9ff1-4487-bc68-c0c44c5d8023)

And the output window:
![image](https://github.com/markolbert/J4JMapControl/assets/105173283/11da2350-1b17-4404-a2c7-269151f1f9fc)

**Comment by markolbert** [comment] 2023-08-24 16:36
Thanx for the info. This is puzzling, as when I look in the main branch on my desktop system the only references I see to those two projects are in Directory.Build.props files. I don't include the .props files in the repository, as a way of letting my development environment use the latest development versions of the libraries while not forcing anyone using the public repository to do the same.

Sorry to have this take so long to resolve, but I'm not terribly experienced myself with git and github :).

Could you do this: do a solution-wide search (ctrl-shift-F) for VisualUtilities.csproj and let me know what you find? That should highlight the specific file(s) where the reference to VisualUtilities.csproj is showing up on your system, which may help me track down what the problem is.

**Comment by NicoMeijerman** [comment] 2023-08-25 14:13
Hi Mark,

I have looked at the sln file, and yes, both project are mentioned, directly in the first part:

`Microsoft Visual Studio Solution File, Format Version 12.00
VisualStudioVersion = 17.4.33213.308
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "J4JMapLibrary", "J4JMapLibrary\J4JMapLibrary.csproj", "{56BA9329-81E8-4D81-8A61-7B991042C913}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "external", "external", "{6808BDD2-C188-4ED8-89F7-51797F8F2F6B}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "tests", "tests", "{DAD30E4E-142A-458E-BC22-84BE6D00026B}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "MapLibTests", "MapLibTests\MapLibTests.csproj", "{33C2A734-4EF9-47A9-91A0-ED64E04C001D}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "VisualUtilities", "..\ProgrammingUtilities\VisualUtilities\VisualUtilities.csproj", "{821EDCAA-4380-4563-AF13-F132F7800B2E}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "J4JMapWinLibrary", "J4JMapWinLibrary\J4JMapWinLibrary.csproj", "{0AFFBB05-1AC9-4C95-9A89-E1574814A016}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WinAppTest", "WinAppTest\WinAppTest.csproj", "{94746227-446B-40ED-8D6D-6E7F99B78057}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WindowsUtilities", "..\ProgrammingUtilities\WindowsUtilities\WindowsUtilities.csproj", "{E1D79138-878A-414D-B51F-95BC6AFE2BAF}"
EndProject`

**Comment by markolbert** [comment] 2023-08-25 21:58
I think I've figured out what the problem is...and, if I'm correct, you've just identified a flaw in the way I've been organizing my Visual Studio solutions for a number of years :).

Try this:

- Remove the **VisualUtilities** project (located at Solution/external/VisualUtilities in the Solution Explorer). You remove it by hitting the delete key, or by right-clicking it and selecting Remove.
- Remove the **WindowsUtilitites** project (located at Solution/external/WindowsUtilities in the Solution Explorer) the same way.
- Remove the **external** folder (located at Solution/external) the same way.

You may get some error messages from Visual Studio. Ignore them.

Try building the project. If my theory is correct it should build correctly.

Here's what I think is happening. Years ago, I got into the habit of adding, to a solution folder ("external"), all my external projects a solution needed. I would then reference them, as a project reference (not a package reference, which involves nuget.org), in whatever local projects they were needed.

I thought I had to do things this way. But I just tested the instructions outlined above on my local copy of J4JMapControl, and the solution builds just fine with those external references (and the external folder) removed. The necessary "pointers" to the local copies of my libraries are simply defined as project references in the various Directory.Build.props files on my local machine (which gives my development environment access to the latest versions of my various libraries -- when I publish stuff to nuget I just ensure I publish all the updated projects at once).

Since you (and anyone else cloning a solution I've published) only want to use the library versions I published to nuget the "external" folder references are irrelevant. Worse yet, as I think you've uncovered, their presence keeps anyone else from building a cloned version of the solution, because Visual Studio tries to validate those "external" references and it can't (naturally not, since they only exist on my development machines).

Let me know what you find out.

**Comment by NicoMeijerman** [comment] 2023-08-26 10:59
Hi Mark,

That did help but I run into the next problem. While building I get the following error message:

![image](https://github.com/markolbert/J4JMapControl/assets/105173283/dd3ae32c-a9bf-4a96-a66e-6981a1a858ae)

And I looked at the path indicated: C:\Program Files\Microsoft Visual Studio\2022\Community\VC does NOT contain a folder called Tools. I am using the latest Visual Studio on a freshly installed laptop. So it might be a leftover from older Visual Studio versions? Although, it does address the 2022 version in the path...

And by the way, thank you so much for picking this up. I think it is becoming a mutual learning experience :-).

Regards, Nico.

**Comment by markolbert** [comment] 2023-08-26 15:09
Did you try searching on the error message? Here’s something I found. 

https://stackoverflow.com/questions/74666115/error-could-not-find-a-part-of-the-path-when-build-the-testing-net-core-applica

**Comment by NicoMeijerman** [comment] 2023-08-26 16:12
I didn't search yet, but I think this is not going to solve the problem. The path is not that long and the folder/file is actually missing. But I will dig into it a bit more.
Can you check whether your system does have a Tools folder in "C:\Program Files\Microsoft Visual Studio\2022\Community\VC"?

**Comment by NicoMeijerman** [comment] 2023-08-26 16:37
Just found https://github.com/microsoft/microsoft-ui-xaml/issues/6403, which looks to be the same problem.
Nuget restore didn't solve it, and apart from that, this thread doesn't contain any answers.
It is clearly related to MSBuild...

**Comment by markolbert** [comment] 2023-08-26 17:04
> I didn't search yet, but I think this is not going to solve the problem. The path is not that long and the folder/file is actually missing. But I will dig into it a bit more. Can you check whether your system does have a Tools folder in "C:\Program Files\Microsoft Visual Studio\2022\Community\VC"?

No, that folder/path does not exist on my system, sorry.

I think this particular error is a configuration/setup/VS issue. You might try raising the issue on support sites.

**Comment by NicoMeijerman** [comment] 2023-08-26 20:07
I did have a look at the output of the Build, and that "Microsoft.UI.Xaml.Markup.Compiler.interop.targets" seems to raise the problem. I also tried different configurations, didn't make any difference.

But I can imagine that you are getting fed up by now ;-). So if you want to close this issue, I am totally okay with that.

`Rebuild started...
Restored C:\Users\EliteBook\source\repos\J4JMapControl\J4JMapLibrary\J4JMapLibrary.csproj (in 16 ms).
Restored C:\Users\EliteBook\source\repos\J4JMapControl\J4JMapWinLibrary\J4JMapWinLibrary.csproj (in 55 ms).
Restored C:\Users\EliteBook\source\repos\J4JMapControl\WinAppTest\WinAppTest.csproj (in 120 ms).
1>------ Rebuild All started: Project: WinAppTest, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: J4JMapWinLibrary, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: MapLibTests, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: J4JMapLibrary, Configuration: Debug Any CPU ------
Restored C:\Users\EliteBook\source\repos\J4JMapControl\MapLibTests\MapLibTests.csproj (in 159 ms).
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018: The "GetLatestMSVCVersion" task failed unexpectedly.
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC'.
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.Directory.EnumerateDirectories(String path)
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at InlineCode.GetLatestMSVCVersion.Execute()
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>Done building project "J4JMapWinLibrary.csproj" -- FAILED.
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018: The "GetLatestMSVCVersion" task failed unexpectedly.
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC'.
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at System.IO.Directory.EnumerateDirectories(String path)
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at InlineCode.GetLatestMSVCVersion.Execute()
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Users\EliteBook\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(285,7): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "WinAppTest.csproj" -- FAILED.
4>J4JMapLibrary -> C:\Users\EliteBook\source\repos\J4JMapControl\J4JMapLibrary\bin\Debug\net7.0\J4JSoftware.J4JMapLibrary.dll
3>MapLibTests -> C:\Users\EliteBook\source\repos\J4JMapControl\MapLibTests\bin\Debug\net7.0\MapLibTests.dll
========== Rebuild All: 2 succeeded, 2 failed, 0 skipped ==========
========== Rebuild started at 21:41 and took 01,359 seconds ==========
`

**Comment by markolbert** [comment] 2023-08-26 23:22
No, I'm not getting fed up. But I'm not sure what more I can add in terms of resolving what appears to be a Visual Studio/configuration issue. Just because I've used the product for many years doesn't mean I know all of its intricacies :).

I have no problem leaving the issue open for now.

**Comment by NicoMeijerman** [comment] 2023-08-27 15:14
Hi Mark,

I tried to build on another laptop, also Windows 11 and Visual Studio Version 17.7.1. And I got the solution building and working! Now I have to figure out what the difference is... So let's close this issue (perhaps after removing those two projects from the solution).

In the meantime, thank you for all your support.

Regards, Nico.

**Comment by markolbert** [comment] 2023-08-27 16:37
That’s awesome, congratulations! I’ll close the issue as soon as I figure out how to resolve the original problem you identified (I’ve asked for advice on Reddit and May post it on stackoverflow, too). 

Btw, it sounds like the VS configurations may be different between the two machines. I think the VS installer lets you export the load/work package config. If so you should be able to export from the working machine and import into the non working machine.

**Comment by markolbert** [comment] 2023-08-28 21:48
Okay, I've figured out how I'm going to handle the original problem you described going forward, so I'm going to close the issue. Please note that I won't be updating the main branch until I finish doing some development work, which may be awhile. In the meantime, deleting those spurious projects from the code you cloned should continue to work.

**Closed by markolbert** 2023-08-28 21:48 UTC
